baseURL = 'https://teaching.wence.uk/comp2221/'
DefaultContentLanguage = 'en'
Language = 'en'
title = 'COMP2221 – Functional Programming'

staticDir = ['static']
disablePathToLower = false
enableGitInfo = true
enableRobotsTXT = false

theme = 'book'

disableKinds = ['taxonomy', 'taxonomyTerm']
# Needed for katex shortcodes
[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableofcontents]
    startlevel = 1
    ordered = false
    endlevel = 4
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'monokailight'
    tabWidth = 8
    
[params]
BookSection = '/'
BookSearch = false
BookComments = false
BookToc = true
BookLogo = 'logo.svg'
BookRepo = 'https://github.com/wenceorg/comp2221'
ModulePage = 'https://www.dur.ac.uk/faculty.handbook/module_description/?year=2021&module_code=COMP2221'
BookEditPath = 'edit/main'
contentDir = 'site/content'
ImageDir = 'images'
CopyRight = '&copy; 2020-- [Lawrence Mitchell](mailto:lawrence@wence.uk) & [Durham University](https://www.dur.ac.uk/).'
