name: Check build

on:
  pull_request:
    branches:
      - main
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.85.0'
        extended: true
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python deps
      run: |
        (test -f requirements.txt && python -m pip install -r requirements.txt) || /bin/true
    - name: Build
      run:
        make html
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v2.5.0
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        target_branch: gh-pages
        build_dir: ./site/public
        keep_history: false
        allow_empty_commit: false
        jekyll: false
        fqdn: teaching.wence.uk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
