name: Publish

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  autobuild-dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Post dispatch
      run: |
        curl -X POST \
             -H "Accept: application/vnd.github.v3+json" \
             -H "Authorization: token ${{ secrets.AUTOBUILD_REPO_PAT }}" \
             https://api.github.com/repos/wenceorg/autobuild-teaching-pages/dispatches \
             -d '{"event_type": "web-update",
                  "client_payload":
                    {"ref": "${{ github.sha }}",
                     "repository": "${{ github.repository }}",
                     "repository_name": "${{ github.event.repository.name}}",
                     "site_location": "site",
                     "build_command": "make html"}}'
